CUSTOMER_UI = r"""<!doctype html>
<html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>PlayZone Manager</title><style>
body{margin:0;background:#08111f;color:#eef5ff;font-family:system-ui,Tahoma,sans-serif}.wrap{max-width:850px;margin:auto;padding:18px}.card{background:#101d2e;border:1px solid #20364e;border-radius:16px;padding:18px;margin:14px 0}.row{display:flex;gap:9px;flex-wrap:wrap}input,button{font:inherit;border-radius:10px;padding:11px}input{background:#091523;color:white;border:1px solid #294661;flex:1;min-width:160px}button{border:0;background:#2678ff;color:white;cursor:pointer}.muted{color:#91a5bd}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px}.stat{background:#0b1726;border-radius:12px;padding:14px}.stat b{font-size:22px;display:block}.hide{display:none}.ok{color:#62d28b}.off{color:#ff8a8a}
</style></head><body><div class="wrap">
<div id="login" class="card"><h2>PlayZone Manager</h2><p class="muted">بوابة العميل</p><div class="row"><input id="code" placeholder="Customer Code — PZM-0001"><input id="u" placeholder="Username"><input id="p" type="password" placeholder="Password"></div><p><button onclick="signin()">دخول</button></p><div id="err" class="off"></div></div>
<div id="app" class="hide"><div class="row" style="justify-content:space-between;align-items:center"><div><h2 id="name"></h2><div id="custCode" class="muted"></div></div><button onclick="logout()">خروج</button></div><div class="grid" id="stats"></div><div class="card"><h3>Edge</h3><div id="edges"></div></div><div class="card"><h3>المرحلة الحالية</h3><p class="muted">الـCloud Core متصل. في المرحلة التالية ستظهر هنا الجلسات، المبيعات، ساعات Multi 3/4 والتقارير الحية من الـEdge.</p></div></div>
</div><script>
let token=localStorage.pzCustomerToken||'';function H(){return {'Authorization':'Bearer '+token,'Content-Type':'application/json'}}
async function api(path,opt={}){const r=await fetch(path,{...opt,headers:{...H(),...(opt.headers||{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.detail||('HTTP '+r.status));return b}
async function signin(){err.textContent='';try{const b=await api('/api/auth/login',{method:'POST',body:JSON.stringify({customer_code:code.value,username:u.value,password:p.value})});token=b.token;localStorage.pzCustomerToken=token;show();load()}catch(e){err.textContent=e.message}}
function logout(){localStorage.removeItem('pzCustomerToken');location.reload()}function show(){login.classList.add('hide');app.classList.remove('hide')}
async function load(){try{const b=await api('/api/customer/overview');name.textContent=b.customer.name;custCode.textContent=b.customer.code;stats.innerHTML=`<div class="stat"><span class="muted">الفرع</span><b>${b.branch?.name||'-'}</b></div><div class="stat"><span class="muted">أجهزة Edge</span><b>${b.edge_devices.length}</b></div><div class="stat"><span class="muted">Events المستلمة</span><b>${b.received_events}</b></div>`;edges.innerHTML=b.edge_devices.length?b.edge_devices.map(x=>`<div class="card"><b>${x.device_name}</b> — <span class="${x.status==='ACTIVE'?'ok':'off'}">${x.status}</span><div class="muted">Version: ${x.app_version||'-'} | Last Seen: ${x.last_seen_at?new Date(x.last_seen_at).toLocaleString('ar-EG'):'-'}</div></div>`).join(''):'<div class="muted">لم يتم ربط جهاز Edge بعد.</div>'}catch(e){if(String(e.message).includes('401'))logout();else err.textContent=e.message}}
if(token){show();load()}
</script></body></html>"""
